sandbox updated so compressing happens in main jobs

diff --git a/2_lm_c/run b/2_lm_c/run
--- a/2_lm_c/run
+++ b/2_lm_c/run
@@ -375,13 +375,13 @@ cat > INPUT_PHY <<EOF_PHY
 EOF_PHY
 
 cat > job <<EOF_job_SLURM
-#!/bin/tcsh
+#!/bin/bash
 #SBATCH --job-name=lm_c_GA
 #SBATCH --output=job.out
 #SBATCH --nodes=${NNODES}
 #SBATCH --ntasks-per-node=${TASKS_PER_NODE}
 #SBATCH --partition=${QUEUE}
-#SBATCH --time=02:30:00
+#SBATCH --time=00:30:00
 #SBATCH --account=${ACCOUNT}
 EOF_job_SLURM
 if [[ $HOST == daint* ]]; then
@@ -400,25 +400,22 @@ cat >> job <<EOF_job
 # Initialization
 set verbose
 set echo
-module load daint-gpu
+#module load daint-gpu
 # set environmental parameters
-module load daint-gpu
 setenv OMP_NUM_THREADS 1
 setenv COSMO_NPROC_NODEVICE ${NPIO_LMC}
-if ( daint104.cscs.ch =~ daint* ) then
-setenv MPICH_RDMA_ENABLED_CUDA 1
-setenv MPICH_G2G_PIPELINE 256
-setenv CRAY_CUDA_MPS 1
-setenv CUDA_VA_RESERVATION_CHUNK_SIZE 4294967296
-else
-setenv MV2_USE_GPUDIRECT 0
-setenv G2G 1
-setenv MV2_IBA_EAGER_THRESHOLD 0
-setenv MV2_SMP_EAGER_THRESHOLD 0
-endif
-# For CLE, according to infos of JPG
 setenv MALLOC_MMAP_MAX_ 0
 setenv MALLOC_TRIM_THRESHOLD_ 536870912
+setenv MV2_ENABLE_AFFINITY 0
+setenv MV2_USE_CUDA 1
+setenv MPICH_RDMA_ENABLED_CUDA 1
+setenv MPICH_G2G_PIPELINE 256
+setenv CRAY_CUDA_PROXY 0
+setenv CUDA_VA_RESERVATION_CHUNK_SIZE 4294967296
+
+
+
+
 
 
 #unlimit
@@ -431,6 +428,13 @@ date
 
 # Run LM in case directory
 ${RUNCMD} -u -n ${NTASKS} ${EXE}
+
+if [[  \$? -eq 0 ]]; then
+    echo "compressing minute output"
+    python ../compress_minute_output.py 
+else
+    echo "simulation failed"
+fi
 
 # echo date
 date
diff --git a/4_lm_f/run b/4_lm_f/run
--- a/4_lm_f/run
+++ b/4_lm_f/run
@@ -381,21 +381,21 @@ EOF_PHY
 
 # setup job
 cat > job <<EOF_job_SLURM
-#!/bin/tcsh
+#!/bin/bash
 #SBATCH --job-name=lm_f_GA
 #SBATCH --output=job.out
 #SBATCH --nodes=${NNODES}
 #SBATCH --ntasks-per-node=${TASKS_PER_NODE}
 #SBATCH --partition=${QUEUE}
-#SBATCH --time=04:30:00
+#SBATCH --time=00:30:00
 #SBATCH --account=${ACCOUNT}
 EOF_job_SLURM
 
 if [[ $HOST == daint* ]]; then
   sed -i '/account=/a\
 #SBATCH --constraint=gpu\
-module load daint-gpu\
-setenv CRAY_CUDA_MPS 1' job
+#module load daint-gpu\
+' job
 fi
 
 if [ "${GPUS_PER_NODE}" -gt 0 ] ; then
@@ -421,6 +421,10 @@ setenv MPICH_RDMA_ENABLED_CUDA 1
 setenv MPICH_G2G_PIPELINE 256
 setenv CRAY_CUDA_PROXY 0
 setenv CUDA_VA_RESERVATION_CHUNK_SIZE 4294967296
+
+
+module load cudatoolkit
+
 #unlimit
 #limit
 # cleanup
@@ -428,9 +432,18 @@ setenv CUDA_VA_RESERVATION_CHUNK_SIZE 4294967296
 
 # echo date
 date
-sleep 120
+sleep 20
 # Run LM in case directory
 ${RUNCMD} -u -n ${NTASKS} ${EXE}
+
+
+if [[  \$? -eq 0 ]]; then
+    echo "compressing minute output"
+    python ../compress_minute_output.py
+else
+    echo "simulation failed"
+fi
+
 
 # echo date
 date
